name: flappy_birds_2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flappybird.png
    - assets/FlappyBird_bg2.png
    - assets/FlappyBird_bgHome.png
    - assets/toppipe.png
    - assets/bottompipe.png
